### ISSUE TITLE
request: set render/screenshot size from scripting

### ISSUE THREAD

**Issue by CGSchwarzMayo** [neurolabusc/surf-ice#11]
Feature request: it would be helpful to have a way to specify the size of the render window (and consequently, the size of SAVEBMP screenshots) via the scripting interface. If I need a script to create and save a render screenshot in a standard size, currently the best way I can find is to resize the window with the mouse, save screenshot, and check/iterate until I can find the desired size. This then cannot be reproduced later from scripting. 

Thank you for your consideration!

**Comment by neurolabusc** [comment]
The new scripting function "savebmp('filename.png',640,480)" will work on some computers. In my brief test, this works on MacOS, but the ambient occlusion is wrong for Windows. YMMV. It is a nice idea, but tricky with OpenGL contexts - in particular some Linux drivers limit the size of the OpenGL context to the resolution of the main monitor.

**Comment by CGSchwarzMayo** [comment]
After the AO scale-invariance fix, this is working perfectly for me (compiled git HEAD on windows). AO in screenshots now matches the screen, and there is no issue saving to sizes larger than the main monitor. Thank you very much!

**Comment by neurolabusc** [comment]
Great. I am closing this issue. The AO is still somewhat influenced by screen resolution. Screen space ambient occlusion (SSAO) is computed based on the display resolution, the bitmap size influences the Nyquist. In addition, more work could be done to compensate for the depth buffer as screen resolution changes.
  For many meshes, computing the curvature and using it as an overlay (`meshcurv()`) will be a better solution. If you use meshcurv, you can turn off the AO with `shaderambientocclusion(0.0)`. This script illustrates this effect:
```
import gl
gl.resetdefaults()
gl.meshload('BrainMesh_ICBM152Left.mz3')
gl.shaderambientocclusion(0.0)
gl.meshcurv()
```
For completeness, one can also use MeshLab to generate a high-quality per-vertex occlusion map with Filters/ColorCreationAndProcessing/AmbientOcclusion.
