### ISSUE TITLE
README.md compile instructions are out of date

### ISSUE THREAD

**Issue by CGSchwarzMayo** [neurolabusc/surf-ice#12]
Trivial: The README.md compile instructions section is out of date and could be updated to list the python4lazarus_package dependency and where to find it.

I also discovered during my first compile that opts.inc reflects (I think?) options for surficeOld, rather than the default version.  From examining _windows.bat I determined that I should replace this with a copy of optsCore.inc, and this solved the error "Program compile error (unspecified)" that I was getting with some of the shaders. It may be helpful for potential contributors to do some combination of a) make the checked-out opts.inc be that from optsCore.inc since this is the "main" version b) add more information to the error; something like: (e.g. "compile-time options prevent the use of this shader; try using surfice binary rather than surficeOld") c) mention the use/variants of opts.inc in the README.md.

These are simply suggestions/observations. I hope you find them helpful! I am not a pascal programmer, so some of this may be more obvious to someone who is.

**Comment by neurolabusc** [comment]
I have updated the readme to reflect the option for python4lazarus as well as the choice between the old (OpenGL 2.1) and Core (OpenGL 3.3) flavors. The old version supports more hardware, but the new version uses the hardware more efficiently, especially if you [view DTI tracks without the "Better but slower" option selected in the Preferences](https://link.springer.com/chapter/10.1007/978-3-319-67159-8_11).
