### ISSUE TITLE
Compile error: aoScale is not defined when $IFDEF COREGL 

### ISSUE THREAD

**Issue by CGSchwarzMayo** [neurolabusc/surf-ice#13]
This is a tiny bug that I presume was introduced in the last commit. 

Compile Project, Mode: Default, Target: surfice.exe: Exit code 1, Errors: 7, Hints: 3
shaderu.pas(1040,3) Note: Local variable "lC" not used
shaderu.pas(1041,3) Note: Local variable "lLen" not used
shaderu.pas(1041,11) Note: Local variable "lN" not used
**shaderu.pas(1315,2) Error: Identifier not found "aoScale"
shaderu.pas(1316,5) Error: Identifier not found "aoScale"
shaderu.pas(1317,4) Error: Identifier not found "aoScale"
shaderu.pas(1319,7) Error: Identifier not found "aoScale"
shaderu.pas(1319,18) Error: Identifier not found "aoScale"
shaderu.pas(1325,47) Error: Identifier not found "aoScale"
shaderu.pas(1329,48) Error: Identifier not found "aoScale"**

I fixed it as attached, but I am not sure if this is the correct way per project and pascal style.

**Comment by CGSchwarzMayo** [comment]
[aoScale.txt](https://github.com/neurolabusc/surf-ice/files/2040537/aoScale.txt)

**Comment by neurolabusc** [comment]
Patch applied.
