### ISSUE TITLE
python4lazarus dependency

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/surf-ice#14]
I am trying to install the newest version: https://github.com/neurolabusc/surf-ice/archive/v1.0.20180622.tar.gz and I am getting the following build log:

```
[32;01m * [39;49;00mPackage:    sci-visualization/surf-ice-1.0.20180622
[32;01m * [39;49;00mRepository: local
[32;01m * [39;49;00mMaintainer: sci@gentoo.org horea.christ@gmail.com
[32;01m * [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
[32;01m * [39;49;00mFEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking surf-ice-1.0.20180622.tar.gz to /var/tmp/portage/sci-visualization/surf-ice-1.0.20180622/work
>>> Source unpacked in /var/tmp/portage/sci-visualization/surf-ice-1.0.20180622/work
>>> Preparing source in /var/tmp/portage/sci-visualization/surf-ice-1.0.20180622/work/surf-ice-1.0.20180622 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-visualization/surf-ice-1.0.20180622/work/surf-ice-1.0.20180622 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-visualization/surf-ice-1.0.20180622/work/surf-ice-1.0.20180622 ...
SetupCompilerFilename: Searching compiler ...
SearchCompilerCandidates Value=fpc File=/usr/bin/fpc
Hint: (lazarus) [RunTool] /usr/bin/fpc "-iWTOTP"
Hint: (lazarus) [RunTool] /usr/bin/fpc "-va" "compilertest.pas"
SetupCompilerFilename: using /usr/bin/fpc
Hint: (lazarus) storing Lazarus directory "/usr/share/lazarus/" Compiler path "/usr/bin/fpc" in "/var/tmp/portage/sci-visualization/surf-ice-1.0.20180622/homedir/.lazarus/environmentoptions.xml"
Error: (lazbuild) Broken dependency: python4lazarus_package
 [31;01m*[0m ERROR: sci-visualization/surf-ice-1.0.20180622::local failed (compile phase):
 [31;01m*[0m   (no error message)
 [31;01m*[0m 
 [31;01m*[0m Call stack:
 [31;01m*[0m     ebuild.sh, line 124:  Called src_compile
 [31;01m*[0m   environment, line 2203:  Called die
 [31;01m*[0m The specific snippet of code:
 [31;01m*[0m       lazbuild -B --lazarusdir="/usr/share/lazarus/" surfice.lpi || die
 [31;01m*[0m 
 [31;01m*[0m If you need support, post the output of `emerge --info '=sci-visualization/surf-ice-1.0.20180622::local'`,
 [31;01m*[0m the complete build log and the output of `emerge -pqv '=sci-visualization/surf-ice-1.0.20180622::local'`.
 [31;01m*[0m The complete build log is located at '/var/tmp/portage/sci-visualization/surf-ice-1.0.20180622/temp/build.log'.
 [31;01m*[0m The ebuild environment file is located at '/var/tmp/portage/sci-visualization/surf-ice-1.0.20180622/temp/environment'.
 [31;01m*[0m Working directory: '/var/tmp/portage/sci-visualization/surf-ice-1.0.20180622/work/surf-ice-1.0.20180622'
 [31;01m*[0m S: '/var/tmp/portage/sci-visualization/surf-ice-1.0.20180622/work/surf-ice-1.0.20180622'
```

I guess I need and am missing the `python4lazarus_package`. I'm lookig to package it for Gentoo so that the dependency can be handled automatically, but I'm not sure where the source code is located. Is it [here](https://github.com/Alexey-T/Python-for-Lazarus)?

**Comment by neurolabusc** [comment]
Yes, I use the Github repository. As noted one the main page, you can set your own opts.inc - if you remove {$DEFINE MYPY} the software should not need this package. However, the dependency may also need to be removed in the project inspector. I have never worked out how to dynamically remove package dependencies (I have requested this feature for the Lazarus IDE).

**Comment by TheChymera** [comment]
Ok, so I installed python4lazarus, but it seems it's not properly detected when I try to build surf-ice. Please see the [full log](https://bpaste.net/show/38c628b6cc79).

Any ideas?

**Comment by neurolabusc** [comment]
I am not familiar with your distro, but it looks like you are building/compiling the package rather than installing it. I think you will want to explore `lazbuild --add-package`.

**Comment by TheChymera** [comment]
Ok, I tried to build with:

```
lazbuild -B --lazarusdir="/usr/share/lazarus/" --build-ide= --add-package python4lazarus/python4lazarus_package.lpk
```

And this seems to work for a bit, and then fails with one of two [[1](https://bpaste.net/show/dba4fbcc571d),[2](https://bpaste.net/show/f9d087af09b7)] access violation errors. Do you perhaps know what installing a lazarus `.lpk` package in the IDE entails? Does the file just get copied somewhere, or do files belonging to *the* lazarus package actually get modified in order for this to happen.

If the latter, the package management might start getting adventurous. IT would be really cool if just copying the file someplace would work.

**Comment by neurolabusc** [comment]
I have no experience with your Linux distribution, and the approach you are taking for Gentoo support is dissimilar to my approach for Debian. I suggest you look at your logs and parse the errors. Perhaps you can work with someone familiar with your distribution. On a quick glance I wonder if the issue is with file permissions, as you are requesting it to build in a specific folder and the system reports a read-only directory. I assume with Gentoo you can not `sudo` during a compile?

```
skipping read only directory /usr/share/lazarus/components/synedit/languages/
...
 lazbuild -B --lazarusdir="/usr/share/lazarus/"
```

**Comment by TheChymera** [comment]
I'm pretty sure it's about file permissions. The problem is, the files under `/usr/share/lazarus` belong to the lazarus package. If other packages start modifying them, there is no way to ascertain that they will be returned to their initial state once those packages are removed by the package manager.

How do you handle this on Debian?

**Comment by neurolabusc** [comment]
On my NeuroDebian VirtualBox Linux with default user (brain) i have Lazarus installed locally, so `which lazarus` returns `/home/brain/lazarus/lazarus`. You may want to look at [this web page](http://wiki.lazarus.freepascal.org/Lazarus_directory_permissions_on_Linux_and_Unix)

**Comment by TheChymera** [comment]
This issue has been solved on gentoo. Commit [on the Gentoo package repository](https://github.com/gentoo/gentoo/commit/8f74cfa80a37687a160ccd2f4d256e1a13f12ff5) and longer description of implementation [on the Lazarus forum](http://forum.lazarus-ide.org/index.php/topic,42622.0.html).

**Comment by neurolabusc** [comment]
Fantastic.
