### ISSUE TITLE
Tracktion

### ISSUE THREAD

**Issue by dwiesen** [neurolabusc/surf-ice#15]
Any idea how to use the tracktion script ?

Thanks a lot.

Cheers, Daniel

**Comment by neurolabusc** [comment]
Tracktion is a stand-alone terminal application, not a script. The [nii_preprocess](https://github.com/neurolabusc/nii_preprocess) repository includes compled copies for MacOS (tracktionOSX) and Linux (tracktionLX). I am happy to compile a Windows executable if you want it. The nit_preprocess.m file provides a Matlab wrapper script for applying Traction to the results of bedpost. We use this to visualize the quality of the fiber tracking (see below for the result of traction visualized with Surfice).

```
Tracktion by Chris Rorden version 14Feb2017
Usage: tracktion [options] basename
 Requires dtifit V1 FA images (basename_V1.nii.gz, basename_FA.nii.gz)
Options
 -a maximum angle bend (degrees, default 45)
 -h show help
 -l minimum length (mm, default 12)
 -o output name (.bfloat, .bfloat.gz or .vtk; default "inputName.vtk")
 -s simplification tolerance (mm, default 0.2)
 -t threshold (FA for dtifit, probability for bedpost) (default 0.15)
 -w waypoint name (up to 8; default: none)
 -x bedpost exponent (0=sample p1/p2 equally, 2=strongly prefer p1, default 0.5)
 -1 smooth (0=no, 1=yes, default 1)
 -2 stepsize (voxels, voxels 0.5)
 -3 minimum steps (voxels, default 1)
 -4 redundant fiber removal threshold (mm, default 0)
 -5 seeds per voxel (default 1)
Examples
 tracktion -t 0.2 -o "~/out/fibers.vtk" "~/img_V1.nii.gz"
 tracktion -w BA44.nii -w BA44.nii "~/img_V1.nii"
 tracktion dyads1.nii.gz"

```
![tracktion](https://user-images.githubusercontent.com/8930807/66403789-32ac0f00-e9b5-11e9-8ce3-3a35f5a282a0.jpg)

**Comment by dwiesen** [comment]
The compiled Linux version is perfectly fine. Thanks for the link to the repository.

Cheers, Daniel
