### ISSUE TITLE
streamline visualisation

### ISSUE THREAD

**Issue by claudebajada** [neurolabusc/surf-ice#16]
There does not seem to be away to recolor streamlines to a single arbitrary color or to have multiple streamline overlays open at the same time. Would this be something that would be possible to introduce?

**Comment by neurolabusc** [comment]
Create your datasets in [TrackVis](http://www.trackvis.org/docs/?subsect=fileformat) format and use multiple `scalar` if you want different colors along a single streamline or use `property` if you want to distinguish different fiber bundles. When you load an image with multiple scalars/properties, new dropdowns and buttons will appear in Surfice that allow you to select what you want to hightlight and how you want it highlighted. 

As an example, consider the [results.trk](https://github.com/johncolby/along-tract-stats) that includes three custom scalars, EFFECT, PVAL and PVAL_CORR. The user can select between the default color (based on Direction) or one of these other measures.

![trakvis](https://user-images.githubusercontent.com/8930807/73668646-250d4a00-4674-11ea-8acf-af4f3ee1afc1.png)

**Comment by claudebajada** [comment]
Thanks! That's the issue. I was using .tck! Will retry with .trk
