### ISSUE TITLE
Access denied to node data

### ISSUE THREAD

**Issue by danielemarinazzo** [neurolabusc/surf-ice#18]
Hi

I get an "Access denied - risk of corruption" error when I import a brainnetviewer node file. I use the windows version.
The node file should be ok, since I manage to open it in MriCroS (and brainnetviewer itself).

thanks!

**Comment by neurolabusc** [comment]
@danielemarinazzo I can not replicate your issue. 
 1. Does choosing the Help/About menu item report you are using v1.0.20190902? If not, can you upgrade to the latest version.
 2. Does the Scripting/Python/node menu item load the included /LBPA40.node file correctly?
 3. Can you attach the node file (or the contents, as it is just a text file).

**Comment by danielemarinazzo** [comment]
hmm.. tried again now, and it worked.
fingers crossed.
thanks!
