### ISSUE TITLE
Overlay color selection

### ISSUE THREAD

**Issue by neurolabusc** [neurolabusc/surf-ice#20]
Daniel Leopold requested a [method to customize color schemes.](https://www.nitrc.org/forum/forum.php?thread_id=11829&forum_id=6713) The latest release ([v1.0.20201102](https://github.com/neurolabusc/surf-ice/releases/latest/) ) provides two methods:

**Method 1:** specify dark and bright red/green/blue colors, e.g. here Overlay 1 will. have colors from purple (255,0,255) to lime green (128,255,128):
```

import gl
gl.meshload('BrainMesh_ICBM152.rh.mz3')
gl.overlayload('motor_4t95vol.nii.gz')
gl.overlaycolor(1,255,0,255,128,255,128)

```
**Method 2:** Generate a new color lookup table - these are simply text files. Hint: if you put this text file inside the Resources/LUT folder, it will be in the pull-down menu when you restart (on MacOS, you need to. “Show Package Contents” to see the Resources folder):
```
import gl
import os
fnm = os.path.expanduser("~")+os.path.sep+'myLUT.clut';
f = open(fnm, "w")
f.write("[INT]\n")
f.write("numnodes=3\n")
f.write("[BYT]\n")
f.write("nodeintensity0=0\n")
f.write("nodeintensity1=128\n")
f.write("nodeintensity2=255\n")
f.write("[RGBA255]\n")
f.write("nodergba0=0|0|0|0\n")
f.write("nodergba1=128|128|0|64\n")
f.write("nodergba2=255|0|0|128\n")
f.close()
gl.meshload('BrainMesh_ICBM152.rh.mz3')
gl.overlayload('motor_4t95vol.nii.gz')
gl.overlaycolorname(1,fnm)
```

**Comment by anbai106** [comment]
Hello,

Thank you for this contribution. Actually, I am a lit bit confused for the code that you used to create the lookup table file: **myLUT.clut**.

I want to create a discrete lookup table for only 20 ROIs, like in FreeSurfer: [.](https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/AnatomicalROI/FreeSurferColorLUT). Do you know where is the documentation for the content in **.clut** file? 
`f.write("[INT]\n")
f.write("numnodes=3\n")
f.write("[BYT]\n")
f.write("nodeintensity0=0\n")
f.write("nodeintensity1=128\n")
f.write("nodeintensity2=255\n")
f.write("[RGBA255]\n")
f.write("nodergba0=0|0|0|0\n")
f.write("nodergba1=128|128|0|64\n")
f.write("nodergba2=255|0|0|128\n")`

I know that in SurFice, we can create an atlas m3z file [(),](https://github.com/neurolabusc/surfice_atlas/issues/1) and I was able to do that! But I like the visualization by adding my atlas as an overlay to athe meshed surface (mni152_2009.curv) and see the gyrus of the brain!

Hao 

Thank you

**Comment by neurolabusc** [comment]
Surfice uses the [MRIcroGL CLUT format](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage) for color lookup tables. The best way to understand these is to run MRIcroGL and choose the Color/ColorEditor menu item. This will display the color table with nodes as shown below. The color editor is interactive: you can click on a node to change the color, and drag the node to change the intensity (horizontal axes) and translucency (alpha, vertical axes). You can control-click on the color editor to save a custom color lookup table.

 In the image below you can see that the `gold` color scheme has four nodes, from left to right you might refer to them as black, brown, copper and white. The black node is completely transparent (node at the bottom of the graph), while the white node is 50% translucent. You can see the impact of the this translucency by choosing the Display/Render and adjusting the translucency. The horizontal axes you can see that the nodes are evenly spaced, which linearly scales them relative to image intensity.

![LUT](https://user-images.githubusercontent.com/8930807/101407632-25d0c700-38a9-11eb-9af2-6701d9ac9276.jpg)

Once you understand this, the text format of the club files make sense. The first section `FLT` lists the default minimum and maximum intensity, which is only relevant for CT scans where intensity is calibrated (Hounsfield units) - these values can be real numbers (aka floats). The second section `INT` defines the number of nodes (here 4) - this value must be an integer. The `BYT` section reports the horizontal position of the four nodes, these are bytes (integer in range 0..255). The `RGBA255` reports the red, green, blue and alpha (translucency) for each node (also integers in the range 0..255):

```
[FLT]
min=0
max=0
[INT]
numnodes=4
[BYT]
nodeintensity0=0
nodeintensity1=85
nodeintensity2=170
nodeintensity3=255
[RGBA255]
nodergba0=0|0|0|0
nodergba1=142|85|14|42
nodergba2=227|170|76|84
nodergba3=255|255|255|128


```

**Comment by anbai106** [comment]
@neurolabusc Very intuitive! The color editor in MRIcroGL is like in Paraview! 

Thank you for this work.
