### ISSUE TITLE
Issue loading surficeOld

### ISSUE THREAD

**Issue by dlevitas** [neurolabusc/surf-ice#22]
I was using surficeOld this morning with no issues; however, when I tried loading it this afternoon, I've been receiving this error message:

```
/N/u/dlevitas/Carbonate/.surficeOld/surficeOld.ini
OpenGL 2.1 with 8/8/8/24 bits of R/G/B/Dpth required. Use glxinfo to test capabilities.
/geode2/home/u020/dlevitas/Carbonate/Surf_Ice/BrainNet/BrainMesh_ICBM152_smoothed.lh.mz3 LH /geode2/home/u020/dlevitas/Carbonate/Surf_Ice/BrainNet/BrainMesh_ICBM152_smoothed.lh.mz3 RH /geode2/home/u020/dlevitas/Carbonate/Surf_Ice/BrainNet/BrainMesh_ICBM152_smoothed.rh.mz3

(surficeOld:30058): GLib-GObject-WARNING **: 14:36:22.227: cannot register existing type 'GdkScreen'

(surficeOld:30058): GLib-CRITICAL **: 14:36:22.227: g_once_init_leave: assertion 'result != 0' failed

(surficeOld:30058): Gdk-CRITICAL **: 14:36:22.228: IA__gdk_screen_get_primary_monitor: assertion 'GDK_IS_SCREEN (screen)' failed

(surficeOld:30058): Gtk-WARNING **: 14:36:22.249: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 0
xrandr : /bin/xrandr
VNC-0 connected 1366x768+0+0 0mm x 0mm
Scale factor:  1.000000000E+00
```

I also tried ```MESA_GL_VERSION_OVERRIDE=3.3 surfice```,  but this produced the same error. I don't recall changing anything of note on my institutions HPC user account, so I'm unsure why I can no longer seem to access the surficeOld GUI.

**Comment by neurolabusc** [comment]
Does glxgears work? Did you try running glxinfo to check for diagnostics? Assuming you are using the [latest stable release](https://github.com/neurolabusc/surf-ice/releases) you may want to follow the advice in the included file `surfice_Linux_Installation.txt`. Specifically, you may want to see if you can run the QT5 version. GTK2 is getting pretty old and support is waning. GTK3 is a major regression from GTK2 as it does not support OpenGL multi-sampling. Therefore, QT is the future for Linux graphics.

**Comment by dlevitas** [comment]
Yes, glxgears works fine for me, and I am indeed using the most recent version of surf-ice. I haven't much to help me in the ```surfice_Linux_Installation.txt``` file, but I've had issues running on my institution's HPC before. I'll reach out to an admin to see if they can assist.

**Comment by neurolabusc** [comment]
This sounds like [this bug](https://xpra.org/trac/ticket/1981), where a gtk3 library breaks gtk2 tools. People suggest the solution is:

```
apt-get remove -y gtk3-nocsd libgtk3-nocsd0
```
If this fixes the problem, you may want to work out which program (perhaps a Unity one) installed these buggy libraries. 

Again, since GTK3 does not allow OpenGL multi-sampling, Surfice targets gtk2 (which is mature but end of life) or QT. The latter is the recommended option going forward.

**Comment by dlevitas** [comment]
Unfortunately the code didn't seem to work for me; however, my solution has been to download surf-ice to my laptop (Windows OS) and use WinSCP to copy the necessary files to myself. This seems more stable, given my past issues with running surf-ice on my HPC.
