### ISSUE TITLE
OpenGL issue

### ISSUE THREAD

**Issue by surchs** [neurolabusc/surf-ice#3]
I downloaded the linux compiled release of surfice and on start got the following error message:
```
Unable to load OpenGL 3.3 found 3.3 (Core Profile) Mesa 12.0.6. Vendor Intel Open Source Technology Center. GLSL 3.30
```
I am on Ubuntu 16.04 on a laptop with onboard graphics. 
[This is my `glxinfo` output](https://gist.github.com/surchs/3c9317ac310aec1466680daa4c4d3361)

**Comment by neurolabusc** [comment]
As noted in the wiki
  https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage#Versions
if your GPU and driver support OpenGL 3.3 (GLSL330) or later you can use either the "surfice" or "surficeOld" executable. If you system only supports OpenGL 2.1 (GLSL 120) you will need to use "surficeOld". The older version can not support some of the advanced shading functions, and it will require more video card memory to display DTI tracks. Beyond that they are equivalent Note OpenGL 3.3 was released in 2010, so you may want to see if your driver can be upgraded to support those features.
