### ISSUE TITLE
assign generated plot to variable | python

### ISSUE THREAD

**Issue by ellendicks** [neurolabusc/surf-ice#30]
Hi Chris,

First of all, many thanks for developing Surf Ice! I'm using it all the time.

I'm currently trying to write a python script that generates the surface plots from different angles (medial, lateral) and for both hemispheres, and then combines them directly into one figure. Generating the plots for different angles and saving them with gl.savebmp in one script works fine for me, but I can't figure out how to assign the individual plots as subplots of a new figure (i.e., without saving them in an intermediate step). So far, I've used os.environ to see whether the generated image would be listed. So, my question is: how is the generated plot stored and is there a way I can retrieve it / assign it to a variable?

Many thanks in advance,
Ellen

**Comment by neurolabusc** [comment]
Sorry, the savebmp() function saves one screenshot at a time. This reflects my workflow of putting text and other legends onto figures using a vector drawing tool like Illustrator or Affinity designer. It is always a challenge to provide the needed inbuilt functions without being overwhelming.

**Comment by ellendicks** [comment]
Many thanks for the clarification!
