### ISSUE TITLE
Scripting: Save multiple views in a single png file

### ISSUE THREAD

**Issue by lilikapa** [neurolabusc/surf-ice#32]
Hi Surf Ice Team,

Is it possible to script different views of two activation maps overlaid on a template (e.g. the lateral, medial and superior views) and save the views in a single figure (.png file)? I would like to create images similar to the ones in BrainNet Viewer combining different views but having two activations maps.

So far, I have tried the following code, but I end up seeing only the medial view:

```
import gl
gl.resetdefaults()
gl.azimuthelevation(270, 0)
gl.meshload('BrainMesh_ICBM152.lh.mz3')
gl.overlayload('path_to_activationmap1/spmT_0016.nii')
gl.overlayminmax(1,2,12)
gl.overlayload('path_to_activationmap2/spmT_0017.nii')
gl.overlayminmax(2,2,5)
gl.colorbarvisible(1)
gl.hemispheredistance(0.62)
gl.azimuthelevation(90,0)
gl.savebmp('path_to_targetdir/Figure_test.png')
```
I am running Surf Ice 1.0.20211006+ 64-bit x86-64 Cocoa LLVM StaticPythonBridge on macOS Monterey Version 12.3.1

Please let me know if you need further information from me. Thank you very much in advance for your help!

Best regards,
Lya Paas

**Comment by ToeKneeFan** [comment]
I think you might have to just `savebmp` after each view change and concatenate the images in another program, e.g., `convert -append` in ImageMagick.

**Comment by neurolabusc** [comment]
@ToeKneeFan is correct.
