### ISSUE TITLE
issue with MacOS Monterey 12.5

### ISSUE THREAD

**Issue by AFurryBear** [neurolabusc/surf-ice#36]
Hello! I really enjoyed working with surf-ice and the rich texture library it provides is always satisfying. 

However recently after i updated my Mac system to Monterey 12.5 (from Big Sur), the python scripts is not working anymore. The error msg shows couldnt find python interpreter. 

Due to the fact macos Monterey removed default system python2.7(There's no Framework anymore, see [here](https://macmule.com/2022/01/29/macos-monterey-12-3-will-remove-python-2-7-usr-bin-python/), I've tried to change default python lib path in preference *.ini file to my anaconda python '~/anaconda3/lib/libpython3.8.dylib'. but it crashed immediately after running python code in scripts. Is that a problem cuz by no permission for anaconda lib? 

now im wondering what could be done to fix the issue. 
Thank you.

**Comment by neurolabusc** [comment]
1. Are you using the [latest version](https://github.com/neurolabusc/surf-ice/releases/tag/v1.0.20211006)? If not, does upgrading resolve the issue.

2. Please copy and paste the information from the `About` box to provide details on the version and your installation. For example:
```
Surf Ice 1.0.20211111 64-bit ARM Cocoa LLVM StaticPythonBridge 
hw.model: MacBookAir10,1
Version 11.6.8 (Build 20G730)
www.mricro.com :: BSD 2-Clause License (opensource.org/licenses/BSD-2-Clause)
PythonBridge
Scale 90.2628
Origin 0.4823x-18.4623x2.7279
Mesh Vertices 57525 Faces 115050 Colors 57525
-71.0000..71.9645  -108.7251..71.8006 -71.5471..77.0029
Track Vertices 0 Faces 0 Count 0
Node Vertices 0 Faces 0
GPU Apple :: OpenGL  4.1 Metal - 71.7.1 :: GLSL 4.10
```

**Comment by AFurryBear** [comment]
Thank you!! yes, mine is the newest version. but I've solved it by rebooting my laptop. 🤣
