### ISSUE TITLE
Feature request: Gentler mesh smoothing

### ISSUE THREAD

**Issue by NotaCS** [neurolabusc/surf-ice#37]
Hi,

I really enjoy using Surfice, and the scripting tool is really convenient.

However, I am using the advanced tool `meshcreate` to generate mesh files from .nii files, and the smoothing is way too aggressive for my purpose as it erodes a lot of features, even relatively big ones. 

Would it be possible to add a parameter to the smoothing method so that it is more or less harsh? 

Thank you and keep up the good work!
Victor

**Comment by neurolabusc** [comment]
You may want to try [nii2mesh](https://rordenlab.github.io/nii2meshWeb/) or as a [stand alone command line tool](https://github.com/neurolabusc/nii2mesh). This provides a lot more control over the parameters.

**Comment by NotaCS** [comment]
Hi Chris,

Thank you for the swift answer!
In the end, I think my data was just too rough (2x2x2mm voxels). So I resampled it to 0.5mm, and it's much better now.
Your tool looks great, and I'm sure I will use it in the near future.

Have a good week,
Victor
